apiVersion: apps/v1
kind: Deployment
metadata:
  name: bhagyalaxmi-deploy
  labels:
    app: bhagyalaxmi-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bhagyalaxmi-app
  template:
    metadata:
      labels:
        app: bhagyalaxmi-app
    spec:
      containers:
      - name: bhagyalaxmi-container
        image: bhagi99/jenkins:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bhagyalaxmi-np-service
  labels:
    app: bhagyalaxmi-app
spec:
  selector:
    app: bhagyalaxmi-app

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8080
